# Generated by Django 5.2.11 on 2026-03-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_address_order_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_group',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('size_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], max_length=10)),
                ('standard_size', models.CharField(blank=True, max_length=5, null=True)),
                ('measurements', models.JSONField(default=dict)),
                ('fabric_source', models.CharField(default='tailor', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clothing_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.clothingtype')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fabric')),
                ('fabric_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fabriccolor')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.pattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
